### ISSUE TITLE
use-package for ox-html etc builtin feature

### ISSUE THREAD

**Issue by schspa** [loveminimal/emacs.d-me#1]
当开启了use-package-always-ensure时，系统会自动在melpa等包管理器中尝试安装use-package的包。
由于ox-html等是builtin的feature，所以安装会失败。建议改用eval-after-load来处理

``` emacs-lisp
(setq-default use-package-always-ensure t)
```
错误log
``` txt
Error (use-package): Failed to install ox-html: Package ‘ox-html-’ is unavailable
Error (use-package): Failed to install ox-publish: Package ‘ox-publish-’ is unavailable
Error (use-package): Failed to install auto-save-and-publish-file-mode: Package ‘auto-save-and-publish-file-mode-’ is unavailable
Error (use-package): Failed to install ox-html: Package ‘ox-html-’ is unavailable
```

**Comment by loveminimal** [comment]
> 当开启了use-package-always-ensure时，系统会自动在melpa等包管理器中尝试安装use-package的包。
> 由于ox-html等是builtin的feature，所以安装会失败。建议改用eval-after-load来处理
> 
> ```emacs-lisp
> (setq-default use-package-always-ensure t)
> ```
> 
> 错误log
> 
> ```
> Error (use-package): Failed to install ox-html: Package ‘ox-html-’ is unavailable
> Error (use-package): Failed to install ox-publish: Package ‘ox-publish-’ is unavailable
> Error (use-package): Failed to install auto-save-and-publish-file-mode: Package ‘auto-save-and-publish-file-mode-’ is unavailable
> Error (use-package): Failed to install ox-html: Package ‘ox-html-’ is unavailable
> ```

Okay ^_^
